name: Create Release Package

on:
  push:
    tags:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Package
        run: zip -j volume_scroller@trflynn89.pm.me.zip volume_scroller@trflynn89.pm.me/*

      - name: Upload Package
        uses: softprops/action-gh-release@v1
        with:
          files: volume_scroller@trflynn89.pm.me.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
