name: Create Release Package

on:
  push:
    tags:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Version
        id: version
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Package Name
        id: package
        run: echo "package=volume_scroller@francislavoie.github.io.${{ steps.version.outputs.tag }}.shell-extension.zip" >> $GITHUB_OUTPUT

      - name: Create Package
        run: |
          cd volume_scroller@francislavoie.github.io
          zip -r ../${{ steps.package.outputs.package }} .

      - name: Upload Package
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.package.outputs.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
